force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto__c/fields/Cosecha__c.field-meta.xml
<CustomField>
    <fullName>Cosecha__c</fullName>
    <label>Cosecha</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Producto__c/fields/Pack__c.field-meta.xml
<CustomField>
    <fullName>Pack__c</fullName>
    <label>Pack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6x1500ml</fullName>
            </value>
            <value>
                <fullName>12x750ml</fullName>
            </value>
            <value>
                <fullName>6x750ml</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Producto__c/fields/URL_Imagen__c.field-meta.xml
<CustomField>
    <fullName>URL_Imagen__c</fullName>
    <label>URL Imagen</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Producto__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Varietales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Varietales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Chardonnay</fullName>
    </customValue>
    <customValue>
        <fullName>Malbec</fullName>
    </customValue>
    <customValue>
        <fullName>Cabernet</fullName>
    </customValue>
    <customValue>
        <fullName>Merlot</fullName>
    </customValue>
    <customValue>
        <fullName>Torrontés</fullName>
    </customValue>
    <customValue>
        <fullName>Rosé</fullName>
    </customValue>
    <customValue>
        <fullName>Malbec 375</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cepas</fullName>
    </customValue>
    <customValue>
        <fullName>Cabernet Franc</fullName>
    </customValue>
    <customValue>
        <fullName>Semillón</fullName>
    </customValue>
    <customValue>
        <fullName>Blanc de Franc</fullName>
    </customValue>
    <masterLabel>Varietales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductosService.cls
/* Clase con método que sirve para buscar en la base de datos registros del objeto producto.  */


public with sharing class ProductosService {
    @AuraEnabled(cacheable=true)
    public static  List<Producto__c> getAllProductos() {

        try {
            List<Producto__c> ListaProductos = [SELECT Name, Variedad__c, Cosecha__c, Pack__c, URL_Imagen__c FROM Producto__c];
            return ListaProductos;
        } catch (Exception) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}